### ISSUE TITLE
Committee application form incorrect permissions

### ISSUE THREAD

**Issue by Alex-CD** [royalhackaway/royalhackaway.github.io#65]
Hi,

The [form](https://docs.google.com/forms/d/e/1FAIpQLSezoZ31p94DtY9k-W0d0T6V0EABOysL0QH6Dtrcc9ZAtsNgmA/formrestricted) for applying for joining the committee (on [this page](https://royalhackaway.com/hackawayv3)) is limited to those in (presumably the Compsoc) google organization.

This is what appears when you click on the link.

![image](https://user-images.githubusercontent.com/10101722/68121402-97e51880-feff-11e9-91e9-9fd704be05d2.png)

**Comment by wessupermare** [comment]
Good catch. Fixed, thanks.

I'm closing this issue. Please reopen it if my fix was unsuccessful.
